#!/usr/bin/env python3
import os, sys
from pathlib import Path
SIMOS_ROOT = Path(os.environ.get('SIMOS_ROOT', '.')).resolve()
SIMOS_CWD = os.environ.get('SIMOS_CWD', '/')
if len(sys.argv) < 2:
    print('touch: missing path')
    sys.exit(1)
path = sys.argv[1]
if path.startswith('/'):
    rp = SIMOS_ROOT / Path(path[1:])
else:
    rp = SIMOS_ROOT / Path(SIMOS_CWD.strip('/') or '.') / Path(path)
rp.parent.mkdir(parents=True, exist_ok=True)
rp.touch()
